// Code generated by entc, DO NOT EDIT.

package provider

import (
	"github.com/fitzix/assassin/schema"
)

const (
	// Label holds the string label denoting the provider type in the database.
	Label = "provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the provider in the database.
	Table = "providers"
	// SourcesTable is the table the holds the sources relation/edge.
	SourcesTable = "sources"
	// SourcesInverseTable is the table name for the Source entity.
	// It exists in this package in order to avoid circular dependency with the "source" package.
	SourcesInverseTable = "sources"
	// SourcesColumn is the table column denoting the sources relation/edge.
	SourcesColumn = "provider_sources"
)

// Columns holds all SQL columns for provider fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	fields = schema.Provider{}.Fields()

	// descName is the schema descriptor for name field.
	descName = fields[0].Descriptor()
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator = descName.Validators[0].(func(string) error)
)
