// Code generated by entc, DO NOT EDIT.

package source

import (
	"github.com/fitzix/assassin/ent/schema"
)

const (
	// Label holds the string label denoting the source type in the database.
	Label = "source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url vertex property in the database.
	FieldURL = "url"
	// FieldSecret holds the string denoting the secret vertex property in the database.
	FieldSecret = "secret"

	// Table holds the table name of the source in the database.
	Table = "sources"
	// VendorTable is the table the holds the vendor relation/edge.
	VendorTable = "sources"
	// VendorInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	VendorInverseTable = "providers"
	// VendorColumn is the table column denoting the vendor relation/edge.
	VendorColumn = "provider_sources"
	// VersionTable is the table the holds the version relation/edge.
	VersionTable = "sources"
	// VersionInverseTable is the table name for the Version entity.
	// It exists in this package in order to avoid circular dependency with the "version" package.
	VersionInverseTable = "versions"
	// VersionColumn is the table column denoting the version relation/edge.
	VersionColumn = "version_sources"
)

// Columns holds all SQL columns for source fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldSecret,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Source type.
var ForeignKeys = []string{
	"provider_sources",
	"version_sources",
}

var (
	fields = schema.Source{}.Fields()

	// descURL is the schema descriptor for url field.
	descURL = fields[0].Descriptor()
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator = descURL.Validators[0].(func(string) error)
)
