// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/fitzix/assassin/ent/provider"
	"github.com/fitzix/assassin/ent/source"
	"github.com/fitzix/assassin/ent/version"
)

// Source is the model entity for the Source schema.
type Source struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Secret holds the value of the "secret" field.
	Secret string `json:"secret,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SourceQuery when eager-loading is set.
	Edges            SourceEdges `json:"edges"`
	provider_sources *int
	version_sources  *int
}

// SourceEdges holds the relations/edges for other nodes in the graph.
type SourceEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Provider
	// Version holds the value of the version edge.
	Version *Version
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SourceEdges) ProviderOrErr() (*Provider, error) {
	if e.loadedTypes[0] {
		if e.Provider == nil {
			// The edge provider was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: provider.Label}
		}
		return e.Provider, nil
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// VersionOrErr returns the Version value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SourceEdges) VersionOrErr() (*Version, error) {
	if e.loadedTypes[1] {
		if e.Version == nil {
			// The edge version was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: version.Label}
		}
		return e.Version, nil
	}
	return nil, &NotLoadedError{edge: "version"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Source) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // url
		&sql.NullString{}, // secret
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Source) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // provider_sources
		&sql.NullInt64{}, // version_sources
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Source fields.
func (s *Source) assignValues(values ...interface{}) error {
	if m, n := len(values), len(source.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field url", values[0])
	} else if value.Valid {
		s.URL = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field secret", values[1])
	} else if value.Valid {
		s.Secret = value.String
	}
	values = values[2:]
	if len(values) == len(source.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field provider_sources", value)
		} else if value.Valid {
			s.provider_sources = new(int)
			*s.provider_sources = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field version_sources", value)
		} else if value.Valid {
			s.version_sources = new(int)
			*s.version_sources = int(value.Int64)
		}
	}
	return nil
}

// QueryProvider queries the provider edge of the Source.
func (s *Source) QueryProvider() *ProviderQuery {
	return (&SourceClient{config: s.config}).QueryProvider(s)
}

// QueryVersion queries the version edge of the Source.
func (s *Source) QueryVersion() *VersionQuery {
	return (&SourceClient{config: s.config}).QueryVersion(s)
}

// Update returns a builder for updating this Source.
// Note that, you need to call Source.Unwrap() before calling this method, if this Source
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Source) Update() *SourceUpdateOne {
	return (&SourceClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Source) Unwrap() *Source {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Source is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Source) String() string {
	var builder strings.Builder
	builder.WriteString("Source(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", url=")
	builder.WriteString(s.URL)
	builder.WriteString(", secret=")
	builder.WriteString(s.Secret)
	builder.WriteByte(')')
	return builder.String()
}

// Sources is a parsable slice of Source.
type Sources []*Source

func (s Sources) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
