// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

var TableNames = struct {
	App         string
	AppCategory string
	AppTag      string
	Carousel    string
	Category    string
	Hot         string
	Provider    string
	Role        string
	Source      string
	Tag         string
	User        string
	Version     string
}{
	App:         "app",
	AppCategory: "app_category",
	AppTag:      "app_tag",
	Carousel:    "carousel",
	Category:    "category",
	Hot:         "hot",
	Provider:    "provider",
	Role:        "role",
	Source:      "source",
	Tag:         "tag",
	User:        "user",
	Version:     "version",
}
