// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Carousel is the predicate function for carousel builders.
type Carousel func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Hot is the predicate function for hot builders.
type Hot func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
